Import data and seperate features and output

In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
clean_data = pd.read_csv("./datasets/cleaned_data.csv")
clean_data["month"] = clean_data["month"].map({
    1: "jan",
    2: "feb",
    3: "mar",
    4: "apr",
    5: "may",
    6: "jun",
    7: "jul",
    8: "aug",
    9: "sep",
    10: "oct",
    11: "nov",
    12: "dec"
})
clean_data.head()

,sn,date,item_id,price,item_count,name,kcal,month,year,day
0,0,2019-01-01,3,29.22,2.0,sweet_fruity_cake,931,jan,2019,1
1,1,2019-01-01,4,26.42,22.0,amazing_steak_dinner_with_rolls,763,jan,2019,1
2,2,2019-01-01,12,4.87,7.0,fantastic_sweet_cola,478,jan,2019,1
3,3,2019-01-01,13,4.18,12.0,sweet_frozen_soft_drink,490,jan,2019,1
4,4,2019-01-01,16,3.21,136.0,frozen_milky_smoothy,284,jan,2019,1

In [3]:
months=pd.get_dummies(clean_data["month"], prefix="month_", dtype=int)
months.head()

,month__apr,month__aug,month__dec,month__feb,month__jan,month__jul,month__jun,month__mar,month__may,month__nov,month__oct,month__sep
0,0,0,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0

In [4]:
names=pd.get_dummies(clean_data["name"], prefix="name_", dtype=int)
names.head()

,name__amazing_cocktail,name__amazing_fish_with_vegetables_meal,name__amazing_frozen_milky_cake,name__amazing_lamb_dinner,name__amazing_pork_lunch,name__amazing_steak_dinner_with_rolls,name__amazing_sweet_breaded_carrot_cake,name__amazing_sweet_fruity_vegetable_cake,name__amazing_trout_with_vegetables_dinner,name__amazing_vegetable_and_bread_dinner,...,name__steak_meal,name__strawberry_smoothy,name__super_sweet_cocktail,name__sweet_breaded_zucchini_cake,name__sweet_frozen_soft_drink,name__sweet_fruity_cake,name__sweet_lamb_cake,name__sweet_savory_cake,name__sweet_vegi_soft_drink,name__vegetarian_plate_with_bread_entree
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df = pd.DataFrame({
    "price": (clean_data["price"] - clean_data["price"].min()) / (clean_data["price"].max() - clean_data["price"].min()),
    "item_count": (clean_data["item_count"] - clean_data["item_count"].min()) / (clean_data["item_count"].max() - clean_data["item_count"].min()),
    "kcal": (clean_data["kcal"] - clean_data["kcal"].min()) / (clean_data["kcal"].max() - clean_data["kcal"].min()),
    "day": (clean_data["day"] - clean_data["day"].min()) / (clean_data["day"].max() - clean_data["day"].min())
})
df = pd.concat([df, months, names], axis=1)
df.head()

,price,item_count,kcal,day,month__apr,month__aug,month__dec,month__feb,month__jan,month__jul,...,name__steak_meal,name__strawberry_smoothy,name__super_sweet_cocktail,name__sweet_breaded_zucchini_cake,name__sweet_frozen_soft_drink,name__sweet_fruity_cake,name__sweet_lamb_cake,name__sweet_savory_cake,name__sweet_vegi_soft_drink,name__vegetarian_plate_with_bread_entree
0,0.529188,0.003509,0.902646,0.0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
1,0.475946,0.038596,0.724868,0.0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,0.066172,0.012281,0.423280,0.0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0.053052,0.021053,0.435979,0.0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,0.034607,0.238596,0.217989,0.0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df = df.sample(frac=1, random_state=42, ignore_index=True)
df.head()

,price,item_count,kcal,day,month__apr,month__aug,month__dec,month__feb,month__jan,month__jul,...,name__steak_meal,name__strawberry_smoothy,name__super_sweet_cocktail,name__sweet_breaded_zucchini_cake,name__sweet_frozen_soft_drink,name__sweet_fruity_cake,name__sweet_lamb_cake,name__sweet_savory_cake,name__sweet_vegi_soft_drink,name__vegetarian_plate_with_bread_entree
0,0.030424,0.000000,0.212698,0.633333,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.109146,0.000000,0.499471,0.133333,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0.068644,0.000000,0.530159,0.700000,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,0.314508,0.059649,0.635979,0.700000,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0.335425,0.000000,0.299471,0.966667,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Split training and testing sets

In [7]:
train_len = math.floor(df.shape[0] * 0.8)
train_len

87680

In [8]:
train_set=df[0:train_len]
test_set=df[train_len:]

Actuall training

In [9]:
import torch

y=torch.tensor(train_set["item_count"].values, dtype=torch.float32, device="cuda")
x=torch.tensor(train_set.drop(columns=["item_count"]).values,dtype=torch.float32, device="cuda", requires_grad=True)

print(x.shape, y.shape)

torch.Size([87680, 108]) torch.Size([87680])

In [10]:
def train_model(x, y, epochs, lr):

    N, d = x.shape

    W = torch.randn(d, 128, device="cuda", requires_grad=True)   # 128 hidden neurons
    B = torch.randn(128, device="cuda", requires_grad=True)

    W1 = torch.randn(128, 1, device="cuda", requires_grad=True)
    B1 = torch.randn(1, device="cuda", requires_grad=True)

    loss_fn = torch.nn.MSELoss()

    for epoch in range(epochs):

        # Forward
        n1 = torch.relu(x @ W + B)      # (N, 100)
        n2 = n1 @ W1 + B1               # (N, 1)

        loss = loss_fn(n2, y)

        loss.backward()

        with torch.no_grad():
            W -= lr * W.grad
            B -= lr * B.grad
            W1 -= lr * W1.grad
            B1 -= lr * B1.grad

        W.grad.zero_()
        B.grad.zero_()
        W1.grad.zero_()
        B1.grad.zero_()
        
        if epoch%1000==0 or epoch==epochs-1:
            print(f"Epoch===>{epoch}, Loss:{loss}")

    return W, B, W1, B1

In [11]:
W, B, W1, B1 = train_model(x, y.view(-1,1), 10000, 0.01)

Epoch===>0, Loss:625.3024291992188
Epoch===>1000, Loss:0.17251674830913544
Epoch===>2000, Loss:0.07571741938591003
Epoch===>3000, Loss:0.04383770376443863
Epoch===>4000, Loss:0.029068995267152786
Epoch===>5000, Loss:0.021000731736421585
Epoch===>6000, Loss:0.01611146703362465
Epoch===>7000, Loss:0.012910157442092896
Epoch===>8000, Loss:0.010711021721363068
Epoch===>9000, Loss:0.009134981781244278
Epoch===>9999, Loss:0.0079629085958004

In [ ]:
print(W.size())

torch.Size([108, 128])